### ISSUE TITLE
Publish to MavenCentral / JCenter

### ISSUE THREAD

**Issue by sir4ur0n** [Sir4ur0n/junit-quickcheck-vavr#3]

**Comment by Allsimon** [comment]
Hello,

Bintray is dying in February 2022: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Can you publish this library on Maven Central please ? :)

**Comment by sir4ur0n** [comment]
Hi,

I don't maintain this anymore (I no longer develop in Java) and publishing to Maven Central is non-trivial, so I won't, but if you or anyone wants to fork and publish to Maven Central, feel free to do so!

And if anyone takes over this project, I don't mind updating the README to point to their fork instead :wink:
